Repository cloudevents/spec, pull requests merged in 2019-06, with the labels that each got.

#432 Type system changes // canonical string representation
  amqp-format.md
  amqp-transport-binding.md
  http-transport-binding.md
  mqtt-transport-binding.md
  spec.md
Labels: v0.3

#405 Size Constraints
  spec.md
Labels: v0.3

#439 Misc. typo fixes
  documented-extensions.md
  nats-transport-binding.md
  primer.md
Labels: v1.0

#447 Update to title format.
  amqp-format.md
  primer.md
  proprietary-specs.md
  spec.md
Labels: v1.0

#450 Remove blank section
  primer.md
Labels: v1.0

#446 Be clearer about "time"
  spec.md
Labels: v1.0

#390 Primer edits - Architecture section
  primer.md
Labels: try-for-v1.0

#440 Add a little clarity around "type"
  spec.md
Labels: try-for-v1.0

#279 Add non-goals for routing information.
  primer.md
Labels: try-for-v1.0

#461 Forwarding OPTIONAL attributes
  primer.md
  spec.md
Labels: v1.0

#337 Kafka transport binding v2
  Makefile
  README.md
  kafka-transport-binding.md
Labels: try-for-v1.0

#462 Modify roadmap with a more clear goal of getting to v1.0
  roadmap.md
Labels: v1.0

#468 Fix some typos and grammatical errors per MS Word
  primer.md
  spec.md
Labels: v1.0
